import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--hide-scrollbars'],defaultViewport:{width:1920,height:1080,deviceScaleFactor:1}});
const page = await browser.newPage();
page.on('pageerror',e=>console.log('PAGEERROR',String(e).slice(0,180)));
await page.goto('http://127.0.0.1:8899/',{waitUntil:'networkidle2'});
await new Promise(r=>setTimeout(r,1200));
await page.evaluate(()=>{const b=document.getElementById('flip-spread').getBoundingClientRect();window.scrollBy(0,b.top+b.height/2-window.innerHeight/2);});
await new Promise(r=>setTimeout(r,1500));
const label = () => page.evaluate(()=>String(document.querySelectorAll('.leaf.is-flipped').length));
console.log('start:', await label());
await page.evaluate(()=>{const b=document.getElementById('flip-next');for(let i=0;i<4;i++)b.click();});
await new Promise(r=>setTimeout(r,5000));
console.log('after 4 rapid "next" clicks :', await label(), '(expect Trang 7 / 12)');
await page.evaluate(()=>{const b=document.getElementById('flip-prev');for(let i=0;i<3;i++)b.click();});
await new Promise(r=>setTimeout(r,4200));
console.log('after 3 rapid "prev" clicks :', await label(), '(expect Trang 1 / 12)');
await page.evaluate(()=>{const b=document.getElementById('flip-prev');b.click();});
await new Promise(r=>setTimeout(r,1400));
console.log('one more "prev" (to cover)  :', await label(), '(expect Bìa trước)');
await browser.close();
