import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
import { PNG } from 'pngjs';
import pixelmatch from 'pixelmatch';
const browser = await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--hide-scrollbars'],defaultViewport:{width:1600,height:1000,deviceScaleFactor:1}});
const page = await browser.newPage();
await page.goto('http://127.0.0.1:8899/',{waitUntil:'networkidle2'});
await new Promise(r=>setTimeout(r,1200));
await page.evaluate(()=>{const b=document.getElementById('flip-spread').getBoundingClientRect();window.scrollBy(0,b.top+b.height/2-window.innerHeight/2);});
await new Promise(r=>setTimeout(r,1500));
await page.evaluate(()=>document.getElementById('flip-next').click());
await new Promise(r=>setTimeout(r,1500));
const bk = await page.evaluate(()=>{const e=document.querySelector('.flip-book__inner');const r=e.getBoundingClientRect();return {x:r.left+scrollX,y:r.top+scrollY,w:r.width,h:r.height};});
const f  = await page.evaluate(()=>{const e=[...document.querySelectorAll('.leaf:not(.is-flipped) .leaf__face--front')].find(x=>x.getBoundingClientRect().width>1);const r=e.getBoundingClientRect();return {x:r.left,y:r.top,w:r.width,h:r.height};});
await page.mouse.move(f.x+f.w-100, f.y+f.h-100);
await new Promise(r=>setTimeout(r,400));
const clip={x:bk.x,y:bk.y,width:bk.w,height:bk.h};
await page.mouse.down(); await page.mouse.up();
/* wait until the turn is ~99% done, then grab the final animated frame */
await page.evaluate(async ()=>{ const t0=performance.now(); while(performance.now()-t0 < 5900) await new Promise(r=>requestAnimationFrame(r)); });
const before = await page.screenshot({clip, encoding:'binary'});
const stillTurning = await page.evaluate(()=>!!document.querySelector('.leaf.is-turning'));
await new Promise(r=>setTimeout(r,900));
const after = await page.screenshot({clip, encoding:'binary'});
const A=PNG.sync.read(before), B=PNG.sync.read(after);
const d=new PNG({width:A.width,height:A.height});
const bad=pixelmatch(A.data,B.data,d.data,A.width,A.height,{threshold:0.12,includeAA:true});
fs.writeFileSync('shots/seam-before.png',before);
fs.writeFileSync('shots/seam-after.png',after);
fs.writeFileSync('shots/seam-diff.png',PNG.sync.write(d));
console.log('captured while still turning:', stillTurning);
console.log('last animated frame vs the page after it lands:');
console.log('  differing pixels', bad, 'of', A.width*A.height, '=', ((1-bad/(A.width*A.height))*100).toFixed(2)+'% identical');
await browser.close();
